import { ICard } from '../../store/storeModels';

export const cards66: ICard[] = [
    {
        id: 1,
        word: 'word1',
        translate: 'Translate',
        theme: 'theme1',
        note: 'note',
        time: Date.now(),
        color: 'red',
        favorite: true,
    },
    {
        id: 2,
        word: 'Word2',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 124,
        color: 'red',
        favorite: true,
    },
    {
        id: 3,
        word: 'word3',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 123,
        color: 'orange',
        favorite: false,
    },
    {
        id: 4,
        word: 'Word4',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 124,
        color: 'orange',
        favorite: false,
    },
    {
        id: 5,
        word: 'word5',
        translate: 'Translate',
        theme: 'theme3',
        note: 'note',
        time: 123,
        color: 'green',
        favorite: true,
    },
    {
        id: 6,
        word: 'Word6',
        translate: 'Translate',
        theme: 'theme3',
        note: 'note',
        time: 124,
        color: 'green',
        favorite: false,
    },
    {
        id: 7,
        word: 'word1',
        translate: 'Translate',
        theme: 'theme1',
        note: 'note',
        time: Date.now(),
        color: 'red',
        favorite: true,
    },
    {
        id: 8,
        word: 'Word2',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 124,
        color: 'red',
        favorite: true,
    },
    {
        id: 9,
        word: 'word3',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 123,
        color: 'orange',
        favorite: false,
    },
    {
        id: 10,
        word: 'Word4',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 124,
        color: 'orange',
        favorite: false,
    },
    {
        id: 11,
        word: 'word5',
        translate: 'Translate',
        theme: 'theme3',
        note: 'note',
        time: 123,
        color: 'green',
        favorite: true,
    },
    {
        id: 12,
        word: 'Word6',
        translate: 'Translate',
        theme: 'theme3',
        note: 'note',
        time: 124,
        color: 'green',
        favorite: false,
    },
    {
        id: 13,
        word: 'word1',
        translate: 'Translate',
        theme: 'theme1',
        note: 'note',
        time: Date.now(),
        color: 'red',
        favorite: true,
    },
    {
        id: 14,
        word: 'Word2',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 124,
        color: 'red',
        favorite: true,
    },
    {
        id: 15,
        word: 'word3',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 123,
        color: 'orange',
        favorite: false,
    },
    {
        id: 16,
        word: 'Word4',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 124,
        color: 'orange',
        favorite: false,
    },
    {
        id: 17,
        word: 'word5',
        translate: 'Translate',
        theme: 'theme3',
        note: 'note',
        time: 123,
        color: 'green',
        favorite: true,
    },
    {
        id: 18,
        word: 'Word6',
        translate: 'Translate',
        theme: 'theme3',
        note: 'note',
        time: 124,
        color: 'green',
        favorite: false,
    },
    {
        id: 19,
        word: 'word1',
        translate: 'Translate',
        theme: 'theme1',
        note: 'note',
        time: Date.now(),
        color: 'red',
        favorite: true,
    },
    {
        id: 20,
        word: 'Word2',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 124,
        color: 'red',
        favorite: true,
    },
    {
        id: 21,
        word: 'word3',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 123,
        color: 'orange',
        favorite: false,
    },
    {
        id: 22,
        word: 'Word4',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 124,
        color: 'orange',
        favorite: false,
    },
    {
        id: 23,
        word: 'word5',
        translate: 'Translate',
        theme: 'theme3',
        note: 'note',
        time: 123,
        color: 'green',
        favorite: true,
    },
    {
        id: 24,
        word: 'Word6',
        translate: 'Translate',
        theme: 'theme3',
        note: 'note',
        time: 124,
        color: 'green',
        favorite: false,
    },
    {
        id: 25,
        word: 'word1',
        translate: 'Translate',
        theme: 'theme1',
        note: 'note',
        time: Date.now(),
        color: 'red',
        favorite: true,
    },
    {
        id: 26,
        word: 'Word2',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 124,
        color: 'red',
        favorite: true,
    },
    {
        id: 27,
        word: 'word3',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 123,
        color: 'orange',
        favorite: false,
    },
    {
        id: 28,
        word: 'Word4',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 124,
        color: 'orange',
        favorite: false,
    },
    {
        id: 29,
        word: 'word5',
        translate: 'Translate',
        theme: 'theme3',
        note: 'note',
        time: 123,
        color: 'green',
        favorite: true,
    },
    {
        id: 30,
        word: 'Word6',
        translate: 'Translate',
        theme: 'theme3',
        note: 'note',
        time: 124,
        color: 'green',
        favorite: false,
    },
    {
        id: 31,
        word: 'word1',
        translate: 'Translate',
        theme: 'theme1',
        note: 'note',
        time: Date.now(),
        color: 'red',
        favorite: true,
    },
    {
        id: 32,
        word: 'Word2',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 124,
        color: 'red',
        favorite: true,
    },
    {
        id: 33,
        word: 'word3',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 123,
        color: 'orange',
        favorite: false,
    },
    {
        id: 34,
        word: 'Word4',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 124,
        color: 'orange',
        favorite: false,
    },
    {
        id: 35,
        word: 'word5',
        translate: 'Translate',
        theme: 'theme3',
        note: 'note',
        time: 123,
        color: 'green',
        favorite: true,
    },
    {
        id: 36,
        word: 'Word6',
        translate: 'Translate',
        theme: 'theme3',
        note: 'note',
        time: 124,
        color: 'green',
        favorite: false,
    },
    {
        id: 37,
        word: 'word1',
        translate: 'Translate',
        theme: 'theme1',
        note: 'note',
        time: Date.now(),
        color: 'red',
        favorite: true,
    },
    {
        id: 38,
        word: 'Word2',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 124,
        color: 'red',
        favorite: true,
    },
    {
        id: 39,
        word: 'word3',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 123,
        color: 'orange',
        favorite: false,
    },
    {
        id: 40,
        word: 'Word4',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 124,
        color: 'orange',
        favorite: false,
    },
    {
        id: 41,
        word: 'word5',
        translate: 'Translate',
        theme: 'theme3',
        note: 'note',
        time: 123,
        color: 'green',
        favorite: true,
    },
    {
        id: 42,
        word: 'Word6',
        translate: 'Translate',
        theme: 'theme3',
        note: 'note',
        time: 124,
        color: 'green',
        favorite: false,
    },
    {
        id: 43,
        word: 'word1',
        translate: 'Translate',
        theme: 'theme1',
        note: 'note',
        time: Date.now(),
        color: 'red',
        favorite: true,
    },
    {
        id: 44,
        word: 'Word2',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 124,
        color: 'red',
        favorite: true,
    },
    {
        id: 45,
        word: 'word3',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 123,
        color: 'orange',
        favorite: false,
    },
    {
        id: 46,
        word: 'Word4',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 124,
        color: 'orange',
        favorite: false,
    },
    {
        id: 47,
        word: 'word5',
        translate: 'Translate',
        theme: 'theme3',
        note: 'note',
        time: 123,
        color: 'green',
        favorite: true,
    },
    {
        id: 48,
        word: 'Word6',
        translate: 'Translate',
        theme: 'theme3',
        note: 'note',
        time: 124,
        color: 'green',
        favorite: false,
    },
    {
        id: 49,
        word: 'word1',
        translate: 'Translate',
        theme: 'theme1',
        note: 'note',
        time: Date.now(),
        color: 'red',
        favorite: true,
    },
    {
        id: 50,
        word: 'Word2',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 124,
        color: 'red',
        favorite: true,
    },
    {
        id: 51,
        word: 'word3',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 123,
        color: 'orange',
        favorite: false,
    },
    {
        id: 52,
        word: 'Word4',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 124,
        color: 'orange',
        favorite: false,
    },
    {
        id: 53,
        word: 'word5',
        translate: 'Translate',
        theme: 'theme3',
        note: 'note',
        time: 123,
        color: 'green',
        favorite: true,
    },
    {
        id: 54,
        word: 'Word6',
        translate: 'Translate',
        theme: 'theme3',
        note: 'note',
        time: 124,
        color: 'green',
        favorite: false,
    },
    {
        id: 55,
        word: 'word1',
        translate: 'Translate',
        theme: 'theme1',
        note: 'note',
        time: Date.now(),
        color: 'red',
        favorite: true,
    },
    {
        id: 56,
        word: 'Word2',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 124,
        color: 'red',
        favorite: true,
    },
    {
        id: 57,
        word: 'word3',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 123,
        color: 'orange',
        favorite: false,
    },
    {
        id: 58,
        word: 'Word4',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 124,
        color: 'orange',
        favorite: false,
    },
    {
        id: 59,
        word: 'word5',
        translate: 'Translate',
        theme: 'theme3',
        note: 'note',
        time: 123,
        color: 'green',
        favorite: true,
    },
    {
        id: 60,
        word: 'Word6',
        translate: 'Translate',
        theme: 'theme3',
        note: 'note',
        time: 124,
        color: 'green',
        favorite: false,
    },
    {
        id: 61,
        word: 'word1',
        translate: 'Translate',
        theme: 'theme1',
        note: 'note',
        time: Date.now(),
        color: 'red',
        favorite: true,
    },
    {
        id: 62,
        word: 'Word2',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 124,
        color: 'red',
        favorite: true,
    },
    {
        id: 63,
        word: 'word3',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 123,
        color: 'orange',
        favorite: false,
    },
    {
        id: 64,
        word: 'Word4',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 124,
        color: 'orange',
        favorite: false,
    },
    {
        id: 65,
        word: 'word5',
        translate: 'Translate',
        theme: 'theme3',
        note: 'note',
        time: 123,
        color: 'green',
        favorite: true,
    },
    {
        id: 66,
        word: 'Word6',
        translate: 'Translate',
        theme: 'theme3',
        note: 'note',
        time: 124,
        color: 'green',
        favorite: false,
    },
];
export const cardsWithOneColorAndFavorite: ICard[] = [
    {
        id: 1,
        word: 'word1',
        translate: 'Translate',
        theme: 'theme1',
        note: 'note',
        time: Date.now(),
        color: 'red',
        favorite: true,
    },
    {
        id: 3,
        word: 'word3',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 123,
        color: 'orange',
        favorite: false,
    },
    {
        id: 5,
        word: 'word5',
        translate: 'Translate',
        theme: 'theme3',
        note: 'note',
        time: 123,
        color: 'green',
        favorite: false,
    },
];

export const cardsWithoutFavorite: ICard[] = [
    {
        id: 1,
        word: 'word1',
        translate: 'Translate',
        theme: 'theme1',
        note: 'note',
        time: Date.now(),
        color: 'red',
        favorite: false,
    },
    {
        id: 3,
        word: 'word3',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 123,
        color: 'orange',
        favorite: false,
    },
    {
        id: 5,
        word: 'word5',
        translate: 'Translate',
        theme: 'theme3',
        note: 'note',
        time: 123,
        color: 'green',
        favorite: false,
    },
];
export const cardsWithGreenColor: ICard[] = [
    {
        id: 1,
        word: 'word1',
        translate: 'Translate',
        theme: 'theme1',
        note: 'note',
        time: Date.now(),
        color: 'green',
        favorite: false,
    },
    {
        id: 3,
        word: 'word3',
        translate: 'Translate',
        theme: 'theme2',
        note: 'note',
        time: 123,
        color: 'green',
        favorite: false,
    },
    {
        id: 5,
        word: 'word5',
        translate: 'Translate',
        theme: 'theme3',
        note: 'note',
        time: 123,
        color: 'green',
        favorite: false,
    },
];
