export const authorizationData = {
    user: {
        id: 1,
        email: 'user@mail.ru',
        isActivated: 0,
        name: '360',
        registrationDate: '23-7-2023',
    },
    isAuth: true,
    currentDictionary: 'default',
    avatar: '',
    isLoading: false,
    updateError: '',
    data: {
        default: {
            selectOptions: [],
            cards: [],
        },
    },
    cards: [
        {
            id: 1,
            word: 'word1',
            translate: 'translate',
            theme: 'theme1',
            note: 'note',
            time: 123,
            color: 'red',
            favorite: true,
        },
        {
            id: 2,
            word: 'Word2',
            translate: 'Translate',
            theme: 'theme2',
            note: 'note',
            time: 124,
            color: 'red',
            favorite: true,
        },
        {
            id: 3,
            word: 'word3',
            translate: 'translate',
            theme: 'theme2',
            note: 'note',
            time: 123,
            color: 'orange',
            favorite: false,
        },
        {
            id: 4,
            word: 'Word4',
            translate: 'Translate',
            theme: 'theme2',
            note: 'note',
            time: 124,
            color: 'orange',
            favorite: false,
        },
        {
            id: 5,
            word: 'word3',
            translate: 'translate',
            theme: 'theme3',
            note: 'note',
            time: 123,
            color: 'green',
            favorite: true,
        },
        {
            id: 6,
            word: 'Word4',
            translate: 'Translate',
            theme: 'theme3',
            note: 'note',
            time: 124,
            color: 'green',
            favorite: false,
        },
    ],
    selectOptions: ['theme1', 'theme2', 'theme3'],
    changeCard: {
        id: 0,
        word: '',
        translate: '',
        theme: '',
        note: '',
        time: 0,
        color: 'red',
        favorite: false,
    },
    selectedTheme: '',
    serverMessage: '',
};
export const authorizationDataWithActivation = {
    user: {
        id: 1,
        email: 'user@mail.ru',
        isActivated: 1,
        name: '360',
        registrationDate: '23-7-2023',
    },
    isAuth: true,
    currentDictionary: 'default',
    avatar: '',
    isLoading: false,
    updateError: '',
    data: {
        default: {
            selectOptions: [],
            cards: [],
        },
    },
    cards: [
        {
            id: 1,
            word: 'word1',
            translate: 'translate',
            theme: 'theme1',
            note: 'note',
            time: 123,
            color: 'red',
            favorite: true,
        },
        {
            id: 2,
            word: 'Word2',
            translate: 'Translate',
            theme: 'theme2',
            note: 'note',
            time: 124,
            color: 'red',
            favorite: true,
        },
        {
            id: 3,
            word: 'word3',
            translate: 'translate',
            theme: 'theme2',
            note: 'note',
            time: 123,
            color: 'orange',
            favorite: false,
        },
        {
            id: 4,
            word: 'Word4',
            translate: 'Translate',
            theme: 'theme2',
            note: 'note',
            time: 124,
            color: 'orange',
            favorite: false,
        },
        {
            id: 5,
            word: 'word3',
            translate: 'translate',
            theme: 'theme3',
            note: 'note',
            time: 123,
            color: 'green',
            favorite: true,
        },
        {
            id: 6,
            word: 'Word4',
            translate: 'Translate',
            theme: 'theme3',
            note: 'note',
            time: 124,
            color: 'green',
            favorite: false,
        },
    ],
    selectOptions: ['theme1', 'theme2', 'theme3'],
    changeCard: {
        id: 0,
        word: '',
        translate: '',
        theme: '',
        note: '',
        time: 0,
        color: 'red',
        favorite: false,
    },
    selectedTheme: '',
    serverMessage: '',
};
export const logoutData: any = { data: { message: 'Вы вышли из аккаунта' } };